version: '3.8'

services:
  postgres: 
    image: postgres
    container_name: pizza-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pizza-postgres
    ports:
      - "5432:5432"
  
  api:
    container_name: pizza-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3333:3333"