version: '3.8'

services:
  postgres: 
    image: postgres
    container_name: pizza-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pizza-postgres
    ports:
      - "5432:5432"
  
  api:
    container_name: pizza-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    # environment:
    #   - DATABASE_URL=postgresql://postgres:pizza-postgres@pizza-db:5432/pizza-db?schema=public

  test:
    container_name: pizza-test
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
      - api
    ports:
      - "8000:8000"
    environment:
      - WAIT_HOSTS= pizza-db:5432, pizza-api:3333