name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DATABASE_URL: '${{ vars.DATABASE_URL }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test


  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run api tests on docker environment
        run: docker-compose up -e DATABASE_URL=$DATABASE_URL --exit-code-from test

    
